image_width: 1440
image_height: 1080
camera_name: hero_hik_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [1797.46, 0.0, 691.47, 0.0, 1796.38, 550.67, 0.0, 0.0, 1.0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.0745, 0.1203, -0.0005, -0.0009, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data:
    [1781.2, 0.0, 690.38, 0.0, 0.0, 1785.91, 550.53, 0.0, 0.0, 0.0, 1.0, 0.0]
